version: "2"

linters:
  default: none
  enable:
    - bodyclose
    #- copyloopvar
    #- depguard
    - dogsled
    #- dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    #- gocritic
    - gocyclo
    #- godox
    #- mnd
    - goprintffuncname
    #- gosec
    - govet
    #- intrange
    - ineffassign
    - lll
    - misspell
    #- nakedret
    - noctx
    #- nolintlint
    #- revive
    #- staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    dupl:
      threshold: 100
    funlen:
      lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - whyNoLint
    gocyclo:
      min-complexity: 30
    godox:
      keywords:
        - FIXME
    mnd:
      # don't include the "operation" and "assign"
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - '0'
        - '1'
        - '2'
        - '3'
      ignored-functions:
        - strings.SplitN
    govet:
      enable:
        - nilness
        - shadow
    errorlint:
      asserts: false
    lll:
      line-length: 300
    misspell:
      locale: US
      ignore-rules:
        - "importas" # linter name
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: true # require an explanation for nolint directives
      require-specific: true # require nolint directives to be specific about which linter is being skipped
    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - test/testdata_etc # test files
    rules:
      - path: (.+)_test\.go
        linters:
          - dupl
          - mnd
          - lll
      - path: (.+)_test.go
        linters:
          - dupl
          - mnd
          - lll
          - testifylint
